### ISSUE TITLE
Start with housekeeping: write csv file from data preparation into gen/../input for the data analysis

### ISSUE THREAD

**Issue by NCPEValen** [course-dprep/team-project-team-1#34]
__Purpose__
Automate the workflow by saving files and loading in files from the right folders in the gen-directory

__Deliverable__
Write final lines of code in the data preparation files that save the file into the gen directory.
Include new lines of code in the analysis files that read in the file from the gen directory

**Comment by lindseycoover** [comment]
This issue was completed in another issue.
